#!/usr/bin/groovy

@Library('muztagh-shared-library@master')

def pipeline = new muztagh.jenkinslib.Pipeline()

node {
    try{
        pipeline.notifiyBuild('STARTED')
        docker.image('maven:3-alpine').inside('-v /root/.m2:/root/.m2') {
            stage('Build') {
                sh 'mvn -B -DskipTests clean package'
            }
            stage('Test') {
                try {
                    sh 'mvn test'
                }
            finally {
                    junit 'target/surefire-reports/*.xml'
                }
            }
            stage('Deliver') {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    } catch(e) {
        currentBuild.result = "FAILED"
        throw e
    } finally {
        notifiyBuild(currentBuild.result)
    }
 }
